# This is a basic workflow

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build Image
        run: |
          docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/dnschecker:latest .

      - name: Publish Image
        run: |
          echo "${{ secrets.PKG_PAT }}" | docker login https://docker.pkg.github.com -u ${{ secrets.PKG_USER }} --password-stdin
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/dnschecker:latest